name: firehose
description: A sample command-line application.
version: 0.1.0
repository: https://github.com/devoncarew/firehose

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^1.6.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
