name: firehose
description: A tool to auto-publish pub packages from GitHub actions.
version: 0.2.0-dev.1
repository: https://github.com/devoncarew/firehose

# Property to allow auto-publishing from the default branch.
auto_publish: true

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.0
  path: ^1.8.0
  pub_semver: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
