# A CI configuration to auto-publish pub packages.
#
# To use this script, make sure the repo is configured to squash PR commits.

name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  auto-publish:
    # Update this to the host GitHub org.
    if: github.repository_owner == 'devoncarew'
    # This is needed to push tags back to the repo.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of the repo. This fetches all commits in order to
      # determine the changed files.
      - name: Check out repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - name: Set up Dart
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d

      # For other repos, this should be `dart pub global activate firehose`
      - name: Pub get
        run: dart pub get

      # For other repos, this should be `dart pub global run firehose`
      - name: Verify changed packages (publish dry-run)
        if: ${{ github.event_name == 'pull_request' }}
        run: dart pub run firehose --verify
        env:
          PR_LABELS: "${{ join(github.event.pull_request.labels.*.name) }}"

      # For other repos, this should be `dart pub global run firehose`
      - name: Publish changed packages
        if: ${{ github.event_name == 'push' }}
        run: dart pub run firehose --publish
        env:
          # Note: this must exist as an action 'Repository secret' on the repo.
          PUB_CREDENTIALS: "${{ secrets.PUB_CREDENTIALS }}"
