# A CI configuration to auto-publish package:firehose.

name: Publish

on:
  pull_request:
    branches: [ main ]
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'devoncarew' }}

    permissions:
      # This is required for authentication using OIDC.
      id-token: write
      # This lets us create comments on the PR.
      pull-requests: write
      # This lets us create and update check runs.
      checks: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46

      - name: Pub get
        run: dart pub get

      - name: Validate packages
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.number }}
        run: dart pub run firehose --verify

      - name: Publish tagged package
        if: ${{ github.event_name == 'push' }}
        run: dart pub run firehose --publish
