# A CI configuration to auto-publish pub packages.

name: Publish

# Callers of this workflow should use it as follows:
#
# name: Publish
# on:
#   pull_request:
#     branches: [ main ]
#   push:
#     tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]
# jobs:
#   publish:
#     uses: devoncarew/firehose/.github/workflows/publish.yml@main

on:
  workflow_call:

jobs:
  publish:
    # These permissions are required for authentication using OIDC and to enable
    # us to create comments on PRs.
    permissions:
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Install firehose
        run: dart pub global activate firehose

      - name: Validate packages
        if: ${{ github.event_name == 'pull_request' }}
        run: dart pub global run firehose --verify

      - name: Publish packages
        if: ${{ github.event_name == 'push' }}
        run: dart pub global run firehose --publish
