# A CI configuration to auto-publish package:firehose.

name: Publish

on:
  pull_request:
    branches: [ main ]
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'devoncarew' }}

    # These permissions are required for authentication using OIDC and to enable
    # us to create comments on PRs.
    permissions:
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46

      - name: Pub get
        run: dart pub get

      - name: Validate packages
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.number }}
        run: dart pub run firehose --verify

      - name: Publish tagged package
        if: ${{ github.event_name == 'push' }}
        run: dart pub run firehose --publish
